#!/usr/bin/env python3
import os
import sys
import glob

MIGRATION_FILE = """# Generated by Django 4.2.15 on 2026-07-06
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_category'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='auth.user',
            ),
        ),
    ]
"""

def main():
    print("="*60)
    print("🔧 Final Migration Fix – Add Owner Field Only")
    print("="*60)

    # Step 1: Delete all 0003 migration files
    print("\n📁 Deleting conflicting 0003 migrations...")
    for f in glob.glob("tenants/migrations/0003_*.py"):
        os.remove(f)
        print(f"   Deleted: {f}")
    for f in glob.glob("tenants/migrations/__pycache__/0003_*.pyc"):
        os.remove(f)
        print(f"   Deleted cache: {f}")

    # Step 2: Create the new migration file
    print("\n📝 Creating clean migration (only adds owner field)...")
    migration_path = "tenants/migrations/0003_add_owner_only.py"
    with open(migration_path, "w") as f:
        f.write(MIGRATION_FILE)
    print(f"   Created: {migration_path}")

    # Step 3: Ask to push
    print("\n📦 Now we need to push this to GitHub.")
    response = input("Do you want to commit and push automatically? (y/n): ").strip().lower()
    if response == 'y':
        import subprocess
        subprocess.run("git add .", shell=True)
        subprocess.run('git commit -m "Fix: Clean migration for tenant owner field"', shell=True)
        subprocess.run("git push origin main", shell=True)
        print("✅ Push completed. Railway will auto-deploy.")
    else:
        print("⏩ Skipping push. Please manually commit and push the changes.")

    print("\n✅ Patcher finished.")
    print("\n📌 After deployment, run this on Railway Console:")
    print("   python3 manage.py showmigrations tenants")
    print("   # If 0003_add_owner_only is shown as [ ] (not applied), run:")
    print("   python3 manage.py migrate tenants")
    print("   # If it says column already exists, run:")
    print("   python3 manage.py migrate tenants --fake")
    print("="*60)

if __name__ == "__main__":
    main()
