#!/usr/bin/env python3
import os
import sys
import shutil
import subprocess
from pathlib import Path

MIGRATION_FILE = Path("tenants/migrations/0006_remove_tenant_db_host_remove_tenant_db_name_and_more.py")
BACKUP_FILE = MIGRATION_FILE.with_suffix(".py.bak")

# Correct content with proper indentation (4 spaces for operations)
CORRECT_CONTENT = '''# Generated by Django 6.0.6 on 2026-07-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_tenant_db_host_remove_tenant_db_name_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='tenant', name='db_host'),
                migrations.RemoveField(model_name='tenant', name='db_name'),
                migrations.RemoveField(model_name='tenant', name='db_password'),
                migrations.RemoveField(model_name='tenant', name='db_port'),
                migrations.RemoveField(model_name='tenant', name='db_user'),
            ],
            database_operations=[],
        ),
    ]
'''

def fix_migration():
    # Backup if exists and not already backed up
    if MIGRATION_FILE.exists():
        shutil.copy2(MIGRATION_FILE, BACKUP_FILE)
        print(f"📦 Backup created: {BACKUP_FILE}")
    else:
        print("❌ Migration file not found. Creating a fresh one.")
        # Ensure directory exists
        MIGRATION_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Write the corrected content
    with open(MIGRATION_FILE, "w") as f:
        f.write(CORRECT_CONTENT)
    print("✅ Migration file fixed (correct indentation).")

def run_migrate():
    print("🔄 Running migrations...")
    result = subprocess.run(
        ["python", "manage.py", "migrate", "--noinput"],
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print("❌ Migration failed:")
        print(result.stderr)
        sys.exit(1)
    print("✅ Migrations applied successfully.")

if __name__ == "__main__":
    fix_migration()
    run_migrate()
