# Generated by Django 6.0.6 on 2026-07-06 09:35
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_owner_only'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS db_host;",
            reverse_sql="ALTER TABLE tenants_tenant ADD COLUMN db_host varchar(100) DEFAULT 'localhost';"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS db_name;",
            reverse_sql="ALTER TABLE tenants_tenant ADD COLUMN db_name varchar(100);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS db_password;",
            reverse_sql="ALTER TABLE tenants_tenant ADD COLUMN db_password varchar(100);"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS db_port;",
            reverse_sql="ALTER TABLE tenants_tenant ADD COLUMN db_port varchar(10) DEFAULT '5432';"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tenants_tenant DROP COLUMN IF EXISTS db_user;",
            reverse_sql="ALTER TABLE tenants_tenant ADD COLUMN db_user varchar(100);"
        ),
        migrations.AlterField(
            model_name='tenant',
            name='category',
            field=models.CharField(default='chakki', max_length=20),
        ),
    ]
