# Generated by Django 6.0.6 on 2026-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('medicine', 'Medicine'), ('food', 'Food'), ('utility', 'Utility'), ('given_loan', 'Given Loan (Udhaar)'), ('taken_loan', 'Taken Loan'), ('other', 'Other')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_credit', models.BooleanField(default=False, help_text='Given to someone (receivable)')),
                ('person_name', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
