# Generated by Django 6.0.6 on 2026-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_worker_alternative_phone_worker_notes_worker_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
