# Generated by Django 6.0.6 on 2026-07-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema_name', models.CharField(max_length=100, unique=True)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_user', models.CharField(blank=True, max_length=100)),
                ('db_password', models.CharField(blank=True, max_length=100)),
                ('db_host', models.CharField(default='localhost', max_length=100)),
                ('db_port', models.CharField(default='5432', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
