# Generated by Django 6.0.6 on 2026-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('chakki', 'Atta Chakki')], default='chakki', max_length=20),
        ),
    ]
