# Generated by Django 4.2.15 on 2026-07-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='jazzcash_name',
            field=models.CharField(blank=True, help_text='Account holder name for JazzCash', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='jazzcash_number',
            field=models.CharField(blank=True, help_text='JazzCash number for payment', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to pay for one period', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_duration_days',
            field=models.IntegerField(default=30, help_text='Number of days per subscription period'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, help_text='When the current subscription expires', null=True),
        ),
    ]
