# Generated by Django 6.0.6 on 2026-07-06 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='owner',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='category',
            field=models.CharField(default='chakki', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
