# Generated by Django 6.0.6 on 2026-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_owner_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='db_user',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='category',
            field=models.CharField(default='chakki', max_length=20),
        ),
    ]
