# Generated by Django 6.0.6 on 2026-07-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_db_host_remove_tenant_db_name_and_more'),
    ]

    operations = []
