# Generated by Django 6.0.6 on 2026-07-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_tenant_db_host_remove_tenant_db_name_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='tenant', name='db_host'),
                migrations.RemoveField(model_name='tenant', name='db_name'),
                migrations.RemoveField(model_name='tenant', name='db_password'),
                migrations.RemoveField(model_name='tenant', name='db_port'),
                migrations.RemoveField(model_name='tenant', name='db_user'),
            ],
            database_operations=[],
        ),
    ]
