# Generated by Django 6.0.6 on 2026-07-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='address',
            field=models.TextField(blank=True, help_text='Address of person'),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='expense',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for transaction', max_length=200),
        ),
    ]
