# Generated by patch_is_regular.py
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0003_chakkicategory_remove_chakkiorder_cleaning_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakkicustomer',
            name='is_regular',
            field=models.BooleanField(default=False, help_text='Regular customer (saved for future orders)'),
        ),
    ]
