# Generated by patch_is_regular.py
from django.db import migrations

def set_existing_as_regular(apps, schema_editor):
    ChakkiCustomer = apps.get_model('chakki', 'ChakkiCustomer')
    ChakkiCustomer.objects.all().update(is_regular=True)

class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0004_chakkicustomer_is_regular'),
    ]

    operations = [
        migrations.RunPython(set_existing_as_regular),
    ]
