# Generated by Django 6.0.6 on 2026-07-06 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0005_set_existing_as_regular'),
        ('tenants', '0005_remove_tenant_db_host_remove_tenant_db_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakkicategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chakkicustomer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chakkiorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chakkiorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chakkisetting',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
