# Generated by Django 6.0.6 on 2026-07-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0006_chakkicategory_tenant_chakkicustomer_tenant_and_more'),
        (('tenants', '0005_remove_tenant_db_host_remove_tenant_db_name_and_more')),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Selling Categories',
            },
        ),
        migrations.CreateModel(
            name='SellingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('kg', 'KG'), ('liter', 'Liter'), ('gram', 'Gram'), ('packet', 'Packet'), ('dozen', 'Dozen'), ('piece', 'Piece'), ('bottle', 'Bottle')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='chakki.sellingcategory')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SellingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_items', to='chakki.chakkiorder')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('selling_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chakki.sellingprice')),
            ],
        ),
    ]
