# Generated by Django 6.0.6 on 2026-07-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0007_sellingcategory_sellingprice_sellingorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakkicategory',
            name='cleaning_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per KG cleaning charge (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='chakkicategory',
            name='grinding_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per KG grinding charge', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chakkisetting',
            name='cleaning_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Per KG (deprecated)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chakkisetting',
            name='grinding_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Per KG (deprecated)', max_digits=10),
        ),
    ]
