# Generated by patcher_fixed.py
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0008_chakkicategory_cleaning_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingprice',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available quantity in stock', max_digits=10),
        ),
    ]
