# Generated by patcher_add_purchase_price.py
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0009_sellingprice_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingprice',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit (for profit calculation)', max_digits=10),
        ),
    ]
