# Generated by Django 6.0.6 on 2026-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0010_sellingprice_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakkiorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='chakkiorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
