# Generated by Django 6.0.6 on 2026-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0011_alter_chakkiorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakkiorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
    ]
