# Generated by Django 6.0.6 on 2026-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0012_alter_chakkiorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakkicategory',
            name='name',
            field=models.CharField(help_text='e.g., Wheat, Rice, Maize', max_length=50),
        ),
        migrations.AlterField(
            model_name='chakkiorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20),
        ),
    ]
