# Generated by Django 6.0.6 on 2026-07-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chakkiorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chakkiorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
