# Generated by Django 6.0.6 on 2026-07-06 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakki', '0002_chakkiorder_amount_paid_chakkiorder_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChakkiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Wheat, Rice, Maize', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chakkiorder',
            name='cleaning_charges',
        ),
        migrations.RemoveField(
            model_name='chakkiorder',
            name='grinding_charges',
        ),
        migrations.RemoveField(
            model_name='chakkiorder',
            name='is_cleaning_done',
        ),
        migrations.RemoveField(
            model_name='chakkiorder',
            name='total_kg',
        ),
        migrations.CreateModel(
            name='ChakkiOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_cleaning_done', models.BooleanField(default=False)),
                ('grinding_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cleaning_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chakki.chakkicategory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chakki.chakkiorder')),
            ],
        ),
    ]
